# Generated by Django 6.1 on 2026-09-01 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('subject_id', models.IntegerField(primary_key=True, serialize=False)),
                ('rank', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('anime_type', models.CharField(max_length=50)),
                ('episodes', models.IntegerField(blank=True, null=True)),
                ('air_date', models.DateField(blank=True, null=True)),
                ('director', models.CharField(blank=True, max_length=200, null=True)),
                ('script_writer', models.TextField(blank=True, null=True)),
                ('voice_actors', models.TextField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('rating_count', models.IntegerField(blank=True, null=True)),
                ('cover_url', models.CharField(blank=True, max_length=500, null=True)),
                ('detail_url', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
