# Generated by Django 5.2.17 on 2026-09-02 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='director',
            field=models.TextField(blank=True, null=True),
        ),
    ]
