# Generated by Django 5.2.17 on 2026-10-05 04:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0006_tag_animetag_usertag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usertag',
            unique_together={('user', 'tag', 'source')},
        ),
    ]
