# Generated by Django 5.2.17 on 2026-10-05 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0007_alter_usertag_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_view_dashboard',
            field=models.BooleanField(default=False),
        ),
    ]
