# Generated by Django 5.2.17 on 2026-10-06 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0008_userprofile_can_view_dashboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='fav_detail',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='name_cn',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='score_detail',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
