# Generated by Django 5.2.17 on 2026-10-07 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0009_anime_fav_detail_anime_name_cn_anime_score_detail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='name_org',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
