# Generated by Django 5.2.17 on 2026-10-07 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0010_anime_name_org'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anime',
            old_name='name_org',
            new_name='name_orig',
        ),
    ]
