# Generated by Django 5.2.17 on 2026-10-09 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0011_rename_name_org_anime_name_orig'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bangumi_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
